# This is a basic workflow to help you get started with Actions

name: update_package_index

# Controls when the workflow will run
on:
  # Triggers the workflow on push requests which add new packages 
  push:
    paths:
    - 'packages/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure GPG Key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
        env: 
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update package indices
        run: |
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          export GPG_TTY=$(tty)
          gpg -vv --default-key "${EMAIL}" --passphrase "$GPG_PASSPHRASE" --batch --yes -abs -o - Release > Release.gpg
          echo -n "$GPG_SIGNING_KEY" | gpg -vv --default-key "${EMAIL}" --passphrase-fd 0 --batch --yes --clearsign -o - Release > InRelease
        env:
          EMAIL: imperial.driverless@gmail.com
          GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        
      - name: Update README with the available packages
        run: |
          sed '/### Currently available packages/q' README.md > README.md.tmp
          sed -n 's/^Package:/- /p' Packages | sort | uniq >> README.md.tmp
          mv README.md.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "mateusz-lichota"
          git config --global user.email "mateusz@lichota.net"

          git add -A
          git commit -m "update package index"
          git push
